#!/usr/bin/env python3

import sys
import json
import requests

# Telegram Chat ID
CHAT_ID = ""

# Read configuration parameters
with open(sys.argv[1]) as alert_file:
    alert_json = json.load(alert_file)

hook_url = sys.argv[3]

# ==========================
# Extract Alert Information
# ==========================

rule = alert_json.get("rule", {})
agent = alert_json.get("agent", {})
data = alert_json.get("data", {})
geo = alert_json.get("GeoLocation", {})
mitre = rule.get("mitre", {})

alert_level = int(rule.get("level", 0))
rule_id = rule.get("id", "N/A")
description = rule.get("description", "N/A")
agent_name = agent.get("name", "N/A")
agent_id = agent.get("id", "N/A")
agent_ip = agent.get("ip", "N/A")

timestamp = alert_json.get("timestamp", "N/A")

src_ip = data.get("srcip", "N/A")
src_port = data.get("srcport", "N/A")
dst_user = data.get("dstuser", "N/A")

country = geo.get("country_name", "Unknown")

mitre_ids = ", ".join(mitre.get("id", []))
mitre_techniques = ", ".join(mitre.get("technique", []))

# ==========================
# Severity Mapping
# ==========================

if alert_level >= 12:
    severity = "🔴 CRITICAL"
elif alert_level >= 8:
    severity = "🟠 HIGH"
elif alert_level >= 5:
    severity = "🟡 MEDIUM"
else:
    severity = "🔵 LOW"

# ==========================
# Build Telegram Message
# ==========================

message = f"""
🚨 *SECURITY OPERATIONS CENTER ALERT*

━━━━━━━━━━━━━━━━━━━━━━
*Alert Information*
━━━━━━━━━━━━━━━━━━━━━━
• Severity      : {severity}
• Rule ID       : {rule_id}
• Alert Level   : {alert_level}
• Description   : {description}

━━━━━━━━━━━━━━━━━━━━━━
*Affected Asset*
━━━━━━━━━━━━━━━━━━━━━━
• Agent Name    : {agent_name}
• Agent ID      : {agent_id}
• Agent IP      : {agent_ip}

━━━━━━━━━━━━━━━━━━━━━━
*Attack Details*
━━━━━━━━━━━━━━━━━━━━━━
• Source IP     : {src_ip}
• Source Port   : {src_port}
• Target User   : {dst_user}
• Country       : {country}

━━━━━━━━━━━━━━━━━━━━━━
*MITRE ATT&CK*
━━━━━━━━━━━━━━━━━━━━━━
• IDs           : {mitre_ids}
• Technique     : {mitre_techniques}

━━━━━━━━━━━━━━━━━━━━━━
*Event Time*
━━━━━━━━━━━━━━━━━━━━━━
{timestamp}

━━━━━━━━━━━━━━━━━━━━━━
Generated by Wazuh SOC Monitoring
━━━━━━━━━━━━━━━━━━━━━━
"""

payload = {
    "chat_id": CHAT_ID,
    "text": message,
    "parse_mode": "Markdown"
}

headers = {
    "Content-Type": "application/json"
}

requests.post(
    hook_url,
    headers=headers,
    data=json.dumps(payload),
    timeout=10
)

sys.exit(0)

